### ISSUE TITLE
Inkscape's inx (xml) file

### ISSUE THREAD

**Issue by lcnittl** [chriskuehl/identify#120]
Is it okay if a make a pull request that adds `inx` to [extensions.py](https://github.com/chriskuehl/identify/blob/master/identify/extensions.py) giving it an `xml` type tag?

`inx` seems to be also used by Adobe InDesign where it is also an `xml` file.

If you do not want to have that added, is there a way to do this locally (config file or similar, preferably in a git repository's (root) folder as I am using identify with [pre-commit](https://github.com/pre-commit/pre-commit))? → Should I rather ask this at pre-commit?

Or is it at some point planned to add a file content based detection of `xml` files (similar to the shebang mode)?

Thanks and have a nice day!

**Comment by asottile** [comment]
yep that sounds fine!

**Comment by lcnittl** [comment]
Thanks!
