### ISSUE TITLE
False Positive for CMake Files x.h.cmake generated files are considered cmake.

### ISSUE THREAD

**Issue by Skylion007** [chriskuehl/identify#125]
See the discussion in CMake-format: https://github.com/cheshirekow/cmake_format/issues/220 . 

Because identify allows anything.anything.cmake, the regex used to find .cmake files can yield false positives for files that have an x.h.cmake extension.

**Comment by asottile** [comment]
I believe the correct extension for those types of files is `.in`

**Comment by asottile** [comment]
(extensions are all-or-nothing, if you have things that are outside normal use cases you can utilize `exclude` to prevent those (mis)named files)
