### ISSUE TITLE
Extensions override (feature proposal)

### ISSUE THREAD

**Issue by lcnittl** [chriskuehl/identify#131]
I am using `identify` in the scope of `pre-commit`. Filtering by types, a strong feature of `pre-commit`, is (to my understanding) achieved by the use of `identify`.

#### State of the Art

`identify` itself has different mechanisms to determine a file's type; among others "guessing" by extension. There is a [large collection of extension-type mappings](../blob/master/identify/extensions.py) shipped with identify, however, there is a lot of software that "masks" specific file types with custom extensions. While the included mapping for most common extensions and types provides a good basis for every user, I am still wondering whether there are some custom extensions that should not be included there, because the same extension might provide different file type (certainly valid for `.cfg`, `cnf` and the like) in different contexts or is very seldomly used.

#### Proposal

I thus propose an extensions/names override feature, which will allow adding or overriding values in `extension.py`'s `EXTENSIONS` and `NAMES` dictionaries.

Source of this override could be a file (`.identify`, `.identify.yaml`, `.identify-config.yaml`?). For the use with `pre-commit` this file could reside in the git root directory, or in a per directory manner (like `.gitignore`) to allow for different contexts within one repository (not saying this is a good habit, but one might be forced to). The `EXTENSIONS` and `NAMES` dictionary data should then by updated with the data from `.identify-config.yaml`, adding new and overriding existing key-val pairs.

Does something like this fit the philosophy of `identify`, or should one rather add also seldomly used extensions (not talking about ambiguously used extensions, which cannot be included) to the mapping? (I am thinking of, for example, `TeXstudio`'s `.txsprofile`, which is an `.ini` file)

Thanks for your consideration,
lcnittl

**Comment by asottile** [comment]
you can always override the pre-commit configuration for these particular special cases with `files` / `exclude` -- that's the intended escape hatch

adding a separate file that needs to be read to perform these operations takes away the simplicity so I'm going to decline this feature request.

**Comment by asottile** [comment]
but yeah, any unambiguous extensions are welcome to be contributed, there's already quite a few obscure ones but as long as they're unambiguous please send patches

**Comment by lcnittl** [comment]
I was expecting that this is too much overhead/complexity, thus my careful wording of _proposal_ vs _request_ 😆.

I will then file some PRs :) Cheers
