### ISSUE TITLE
(Base)Extensions (feature proposal)

### ISSUE THREAD

**Issue by lcnittl** [chriskuehl/identify#134]
The `NAMES` use some sort of inheriting system from base extensions:

https://github.com/chriskuehl/identify/blob/61deb722cf4dd6a82d57f2e242b208da2fb84bc2/identify/extensions.py#L212-L214

If one could apply this to extensions as well, then

    EXTENSIONS = {
        ..
        'gpx': {'text', 'gpx', 'xml'},
        ..
        'inx': {'text', 'xml', 'inx'},
        ..
        'kml': {'text', 'kml', 'xml'},
        ..
        'svg': {'text', 'image', 'svg', 'xml'},
        ..
        'xml': {'text', 'xml'},
        ..
        'xsd': {'text', 'xml', 'xsd'},
        'xsl': {'text', 'xml', 'xsl'},
        ..
        'yin': {'text', 'xml', 'yin'},
        ..
    }

would change to

    BASEEXTENSIONS = {  # EXTENSIONS ? Would leave NAMES unchanged.
        ..
        'xml': {'text', 'xml'},
        ..
    }
    
    EXTENSIONS = {  # DERIV_EXTENSIONS ?
        'gpx': BASEEXTENSIONS ['xml'] | {'gpx'},
        'inx': BASEEXTENSIONS ['xml'] | {'inx'},
        'kml': BASEEXTENSIONS ['xml'] | {'kml'},
        'svg': BASEEXTENSIONS ['xml'] | {'image', 'svg'},
        'xsd': BASEEXTENSIONS ["xml"] | {'xsd'},
        'xsl': BASEEXTENSIONS ["xml"] | {'xsl'},
        'yin': BASEEXTENSIONS ["xml"] | {'yin'},
    }

inheriting all types of the base extension (even if they change in the future) without textual duplicating them. The base extnesion would always be the one where extension and type are the same (like 'ini' in this example)

Eventually, these 2 dicts will be merged and processed as usual. This could even happen in `extensions.py`, leaving the code base of `identify untouched`:

    EXTENSIONS.update(BASEEXTENSIONS)

This would also serve as some sort of simple aliasing system for extensions like `yml` and `yaml`. Although here, the impossible `{'yaml', 'yml'}: {'text', 'yaml'}` would be smoother...

Thank you for your consideration!

**Comment by lcnittl** [comment]
Hmm, well actually aliasing like this would work if one used a tuple as key

    BASEEXTENSIONS = {  # EXTENSIONS ? Would leave NAMES unchanged.
        'xml': {'text', 'xml'},
        ('yaml', 'yml'): {'text', 'yaml'}
    }


Which could then easily be de-aliased:

    ALIASFREE_EXTENSIONS = {}

    for key, val in BASEEXTENSIONS.items():
        if type(key) == tuple:
            for item in key:
                ALIASFREE_EXTENSIONS[item] = val
        else:
            ALIASFREE_EXTENSIONS[key] = val

giving

    In [1]: ALIASFREE_EXTENSIONS
    Out[1]: {'xml': {'text', 'xml'}, 'yaml': {'text', 'yaml'}, 'yml': {'text', 'yaml'}}

But his probably adds to much processing overhead, right?

**Comment by asottile** [comment]
I don't think this is worth doing, the simple list that we already have works well enough -- interesting idea though
