### ISSUE TITLE
Should we release v1.0.0 to indicate a stable api?

### ISSUE THREAD

**Issue by asottile** [chriskuehl/identify#17]

**Comment by chriskuehl** [comment]
Let's do it. The only thing I'm not totally happy with in the API is the cli's name (`identify-cli`), but I don't have a better alternative... thanks imagemagick :(

**Comment by asottile** [comment]
will do!

**Comment by asottile** [comment]
https://github.com/chriskuehl/identify/releases/tag/v1.0.0
