### ISSUE TITLE
.puml files? 

### ISSUE THREAD

**Issue by iilei** [chriskuehl/identify#89]
As the [plantuml docs](https://plantuml.com/de/preprocessing) suggest the extension `.puml` -- do you mind adding it?

Or should file a merge request?

**Comment by asottile** [comment]
would you like to send a patch?

**Comment by asottile** [comment]
via #90

**Comment by asottile** [comment]
(just a tip for the future, if you put "Closes #89" in your PR it will auto-close for you upon merging)
