### ISSUE TITLE
tests are missing from pypi sdist tarball

### ISSUE THREAD

**Issue by dvzrv** [chriskuehl/identify#95]
Hi! I'm packaging python-identify for Arch Linux.
We usually use the pypi sdist tarballs for packaging, as pypi.org offers a unique naming interface for tarballs (which is important in a build environment).
It would be great, if the tests could be included in an upcoming release of the sdist on pypi.org, as they ensure, that users can run tests against their environment before using a package.

**Comment by asottile** [comment]
hi, please use the github source tgz -- thanks!
