### ISSUE TITLE
SVG file not tagged as "image"

### ISSUE THREAD

**Issue by dkolepp** [chriskuehl/identify#97]
SVG files do not include an "image", but the are images (as indicated in the following references):

* https://fileinfo.com/extension/svg
* https://en.wikipedia.org/wiki/Scalable_Vector_Graphics

Can the entry in `extensions.py` be updated from:

```python
'svg': {'text', 'svg'},
```
to:
```python
'svg': {'text', 'image', 'svg'},
```
?

**Comment by asottile** [comment]
sure, sounds good -- would you please send a patch?

**Comment by dkolepp** [comment]
sure thing.
